apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      containers:
      - name: admin-service
        image: meal-provider-admin-service:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: backend-config
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:password@postgres-admin:5432/meal_provider_admin"
        - name: POSTGRES_HOST
          value: "postgres-admin"
        - name: POSTGRES_DB
          value: "meal_provider_admin"
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: admin-service 