apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: meal-provider
data:
  # 共用配置
  SECRET_KEY: "your-secret-key-here"
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  
  # 數據庫配置
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "password"
  POSTGRES_CONNECT_TIMEOUT: "30"
  POSTGRES_CONNECT_RETRIES: "5"
  POSTGRES_RETRY_INTERVAL: "5"
  
  # 服務 URL 配置
  USER_SERVICE_URL: "http://user-service:8000"
  ORDER_SERVICE_URL: "http://order-service:8000"
  ADMIN_SERVICE_URL: "http://admin-service:8000"
  
  # RabbitMQ 配置
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: "admin"
  RABBITMQ_PASSWORD: "password"
  RABBITMQ_CONNECT_TIMEOUT: "30"
  RABBITMQ_CONNECT_RETRIES: "5"
  RABBITMQ_RETRY_INTERVAL: "5"
  
  # 日誌配置
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
  
  # 服務配置
  SERVICE_PORT: "8000"
  SERVICE_HOST: "0.0.0.0"
  SERVICE_TIMEOUT: "30"
  SERVICE_RETRIES: "3"
  
  # 健康檢查配置
  HEALTH_CHECK_INTERVAL: "30"
  HEALTH_CHECK_TIMEOUT: "10"
  HEALTH_CHECK_RETRIES: "5"
  
  # 安全配置
  CORS_ORIGINS: "*"
  CORS_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
  CORS_HEADERS: "Content-Type,Authorization"
  CORS_MAX_AGE: "3600"
  
  # 性能配置
  MAX_CONNECTIONS: "100"
  CONNECTION_TIMEOUT: "30"
  REQUEST_TIMEOUT: "30" 