apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  # 共用配置
  SECRET_KEY: "your-secret-key-here"
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  
  # 數據庫配置
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "password"
  
  # 服務 URL 配置
  USER_SERVICE_URL: "http://user-service:8000"
  ORDER_SERVICE_URL: "http://order-service:8000"
  ADMIN_SERVICE_URL: "http://admin-service:8000"
  
  # RabbitMQ 配置
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: "admin"
  RABBITMQ_PASSWORD: "password" 