apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: meal-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: ghcr.io/yunycu/meal-provider-order-service:latest
        ports:
        - containerPort: 8000
          name: http
        envFrom:
        - configMapRef:
            name: backend-config
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:password@postgres-order:5432/meal_provider_order"
        - name: POSTGRES_HOST
          value: "postgres-order"
        - name: POSTGRES_DB
          value: "meal_provider_order"
        - name: SERVICE_NAME
          value: "order-service"
        resources:
          requests:
            cpu: "300m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 10
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: meal-provider
spec:
  ports:
  - port: 8000
    targetPort: http
    name: http
  selector:
    app: order-service 