apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: meal-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: meal-provider-user-service:latest
        ports:
        - containerPort: 8000
          name: http
        envFrom:
        - configMapRef:
            name: backend-config
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:password@postgres-user:5432/meal_provider_user"
        - name: POSTGRES_HOST
          value: "postgres-user"
        - name: POSTGRES_DB
          value: "meal_provider_user"
        - name: SERVICE_NAME
          value: "user-service"
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 10
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: meal-provider
spec:
  ports:
  - port: 8000
    targetPort: http
    name: http
  selector:
    app: user-service 