apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-user-config
  namespace: meal-provider
data:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  POSTGRES_DB: meal_provider_user
  PGDATA: /var/lib/postgresql/data/pgdata
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-order-config
  namespace: meal-provider
data:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  POSTGRES_DB: meal_provider_order
  PGDATA: /var/lib/postgresql/data/pgdata
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-admin-config
  namespace: meal-provider
data:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  POSTGRES_DB: meal_provider_admin
  PGDATA: /var/lib/postgresql/data/pgdata 