apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  # API 服務配置
  VITE_USER_SERVICE_URL: "http://user-service:8000"
  VITE_ORDER_SERVICE_URL: "http://order-service:8000"
  VITE_ADMIN_SERVICE_URL: "http://admin-service:8000"
  
  # 環境配置
  NODE_ENV: "production"
  VITE_API_TIMEOUT: "30000" 