apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: meal-provider
spec:
  type: NodePort
  ports:
  - port: 5672
    targetPort: 5672
    name: amqp
  - port: 15672
    targetPort: 15672
    name: management
    nodePort: 30672
  selector:
    app: rabbitmq 