apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: meal-provider
data:
  RABBITMQ_DEFAULT_USER: admin
  RABBITMQ_DEFAULT_PASS: password
  RABBITMQ_ERLANG_COOKIE: secret-cookie 