apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-config
  namespace: meal-provider
data:
  # 備份配置
  BACKUP_RETENTION_DAYS: "7"
  BACKUP_SCHEDULE: "0 0 * * *"  # 每天午夜執行
  BACKUP_PATH: "/backup"
  
  # 數據庫配置
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "password"
  
  # 備份目標
  BACKUP_TARGETS: |
    postgres-user:meal_provider_user
    postgres-order:meal_provider_order
    postgres-admin:meal_provider_admin 