apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
spec:
  schedule: "0 0 * * *"  # 每天午夜執行
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: postgres-backup
            image: postgres:13
            command:
            - /bin/sh
            - -c
            - |
              pg_dump -h postgres-user -U postgres -d meal_provider_user > /backup/user_$(date +%Y%m%d).sql
              pg_dump -h postgres-order -U postgres -d meal_provider_order > /backup/order_$(date +%Y%m%d).sql
              pg_dump -h postgres-admin -U postgres -d meal_provider_admin > /backup/admin_$(date +%Y%m%d).sql
            env:
            - name: PGPASSWORD
              value: password
            volumeMounts:
            - name: backup-volume
              mountPath: /backup
          volumes:
          - name: backup-volume
            persistentVolumeClaim:
              claimName: postgres-backup-pvc
          restartPolicy: OnFailure 