name: Backend Tests

on:
  push:
    branches:
      - backend-dev

jobs:
  Order-Service-Tests:
    runs-on: ubuntu-latest
    steps:
    #Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2
    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r backend/requirements.txt

    # Run order service tests
    - name: Run order_service tests
      run: |
        cd backend/order_service
        IS_TEST=true pytest tests/ --cov=order_service

  User-Service-Tests:
    runs-on: ubuntu-latest
    steps:
    #Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2
    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r backend/requirements.txt
    
    # Run user service tests
    - name: Run user_service tests
      run: |
        cd backend/user_service
        pytest tests/ -v -k "not rabbitmq and not super_admin"

    # Run super admin tests
    - name: Run super admin tests
      run: |
        cd backend/user_service
        pytest tests/test_super_admin.py -v

  Admin-Service-Tests:
    runs-on: ubuntu-latest
    steps:
    #Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2
    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r backend/requirements.txt

    # Run admin service tests
    - name: Run admin_service tests
      run: |
        cd backend/admin_service
        pytest tests/test_main.py
        pytest tests/test_report_analytics.py
        pytest tests/test_billing.py       